version: '3.8'

services:
  db:
    image: mariadb:11.1
    container_name: bloodpressure-db
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=bloodpressuredb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: bloodpressure-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/bloodpressuredb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped

volumes:
  db_data:
